# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
  # used by gh pages
  install:
    aliases: [i]
    cmd: npm install
  # used by gh pages
  build:
    summary: |
      Build complete webpage for production.

      The build output paths are configured in `./svelte.config.js`
      and they assume a _speific directory structure_ outside of this repository.
    aliases: [b]
    cmds:
      - npm run build
      - task: link
  dev:
    summary: |
      Run the page in development mode.
      This mode does not require any prerequisites.
    aliases: [d]
    cmd: npm run dev
  pdf:
    cmds:
      # pandoc \
      # -f gfm \
      # -t html5 \
      # --css src/routes/fonts.css \
      # --css src/routes/layout.css \
      # --css pdf.css \
      # src/lib/burning_stars.md \
      # --pdf-engine wkhtmltopdf \
      # --resource-path=. \
      # -o ./burning_stars.pdf \
      # --verbose
      - |
        pandoc \
          src/lib/burning_stars.md \
          \
          --from markdown+yaml_metadata_block \
          --to pdf \
          --pdf-engine wkhtmltopdf \
          --template src/lib/pandoc/template.html \
          \
          --lua-filter \
            src/lib/pandoc/filters/link.lua \
          --lua-filter \
            src/lib/pandoc/filters/book_citation.lua \
          \
          --css \
            src/routes/normalize.css \
          --css \
            src/routes/fonts.css \
          --css \
            src/routes/layout.css \
          --css \
            src/lib/pandoc/css/book_citation.css \
          \
          --output burning_stars.pdf \
  lint:
    cmds:
      - task: lint:spellcheck
  lint:spellcheck:
    summary: Runs cspell linter with `./.cspell.yaml` tree of configurations
    cmd: cspell ./src/lib/burning_stars.mdx
  # used by gh pages
  link:
    cmds:
      # with each production build chunk names are different,
      # so we will copy entire html with svelte bootstrap scripts
      # to hugo's domain,
      # and, as paths are relative,
      # it will be no issue for hugo-based initial route resolution
      - cp ./../../static/entries/rebis-theory/index.html ./../../layouts/entries/single.html
      # - cp static/entries/rebis-theory/index.html layouts/entries/single.html
